# Generated by Django 4.1 on 2023-03-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mech', 'Mech'), ('Civil', 'Civil')], default='CSE', max_length=100, null=True)),
                ('year', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')])),
                ('sem', models.CharField(choices=[('odd', 'Odd'), ('even', 'Even')], max_length=20)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='department',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='year',
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mech', 'Mech'), ('Civil', 'Civil')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mech', 'Mech'), ('Civil', 'Civil')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.AddField(
            model_name='subject',
            name='staff',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.staff'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_1', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_2', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_3', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_4', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_5', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_6', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_7', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period_8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_8', to='main.subject'),
        ),
    ]
