# Generated by Django 4.1 on 2023-04-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_studentattendance_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
