# Generated by Django 4.1 on 2023-04-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_timetable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateField(),
        ),
    ]
