# Generated by Django 4.1 on 2023-04-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_timetable_date_timetable_p1reason_timetable_p2reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='p1reason',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='p2reason',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='p3reason',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='p4reason',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='p5reason',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='p6reason',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='p7reason',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='p8reason',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='p1reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='p2reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='p3reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='p4reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='p5reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='p6reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='p7reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='p8reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
