# Generated by Django 4.1 on 2023-04-04 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_timetable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
