# Generated by Django 4.1 on 2023-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_timetable_p1reason_remove_timetable_p2reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Mother_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
