# Generated by Django 4.1 on 2023-04-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_student_father_name_alter_student_mother_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Roll_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
