# Generated by Django 4.1 on 2023-04-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_student_door_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Admission_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
